name: want_cmnext
channels:
  - defaults
  - pytorch
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotli-python=1.0.9=py38h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - certifi=2024.8.30=py38h06a4308_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.13.3=h4a9f257_0
  - gmp=6.3.0=h6a678d5_0
  - gnutls=3.6.15=he1e5248_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jpeg=9f=h5ce9db8_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h6a678d5_0
  - libdeflate=1.22=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libpng=1.6.50=h2ed474d_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtasn1=4.20.0=ha30cf84_0
  - libtiff=4.5.1=hffd6297_1
  - libunistring=0.9.10=h27cfd23_0
  - libwebp-base=1.6.0=hb7bb969_0
  - libxcb=1.17.0=h9b100fa_0
  - lz4-c=1.9.4=h6a678d5_1
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py38h5eee18b_1
  - mkl_fft=1.3.8=py38h5eee18b_0
  - mkl_random=1.2.4=py38hdb19cb5_0
  - ncurses=6.5=h7934f7d_0
  - nettle=3.7.3=hbbd107a_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.0.18=hd6dcaed_0
  - pillow=10.4.0=py38h5eee18b_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.20=he870216_0
  - pytorch=1.12.1=py3.8_cuda11.3_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - readline=8.3=hc2a1206_0
  - sqlite=3.51.0=h2a70700_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.15=h54e0aa7_0
  - torchaudio=0.12.1=py38_cu113
  - torchvision=0.13.1=py38_cu113
  - typing_extensions=4.11.0=py38h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=hd233ad5_2
  - zstd=1.5.6=hc292b87_0
  - pip:
      - absl-py==1.2.0
      - addict==2.4.0
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - asttokens==2.0.5
      - attrs==21.4.0
      - backcall==0.2.0
      - bleach==4.1.0
      - cachetools==5.0.0
      - cffi==1.17.1
      - charset-normalizer==2.1.1
      - coloredlogs==15.0.1
      - contourpy==1.1.1
      - cupy-cuda11x==12.3.0
      - cycler==0.11.0
      - cython==0.29.37
      - dataclasses==0.6
      - debugpy==1.5.1
      - decorator==4.4.2
      - defusedxml==0.7.1
      - descartes==1.1.0
      - easydict==1.9
      - einops==0.4.1
      - entrypoints==0.4
      - executing==0.8.3
      - fastrlock==0.8.3
      - fire==0.4.0
      - flatbuffers==25.9.23
      - fonttools==4.57.0
      - fvcore==0.1.5.post20220512
      - google-auth==2.11.0
      - google-auth-oauthlib==0.4.6
      - graphviz==0.20.3
      - grpcio==1.48.1
      - h5py==3.11.0
      - hdf5plugin==5.1.0
      - humanfriendly==10.0
      - idna==3.3
      - imageio==2.35.1
      - imageio-ffmpeg==0.5.1
      - importlib-metadata==4.12.0
      - importlib-resources==5.4.0
      - iopath==0.1.10
      - ipykernel==6.9.1
      - ipython==8.1.0
      - ipython-genutils==0.2.0
      - ipywidgets==7.6.5
      - jedi==0.18.1
      - jinja2==3.0.3
      - joblib==1.1.0
      - jsonschema==4.4.0
      - jupyter==1.0.0
      - jupyter-client==7.1.2
      - jupyter-console==6.4.0
      - jupyter-core==4.9.2
      - jupyterlab-pygments==0.1.2
      - jupyterlab-widgets==1.0.2
      - kiwisolver==1.3.2
      - llvmlite==0.39.1
      - markdown==3.4.1
      - markdown-it-py==3.0.0
      - markupsafe==2.1.1
      - matplotlib==3.4.3
      - matplotlib-inline==0.1.3
      - mdurl==0.1.2
      - mistune==0.8.4
      - mmcv-full==1.6.1
      - moviepy==1.0.3
      - mpmath==1.3.0
      - nbclient==0.5.11
      - nbconvert==6.4.2
      - nbformat==5.1.3
      - nest-asyncio==1.5.4
      - notebook==6.4.8
      - numba==0.56.4
      - numpy==1.22.4
      - nuscenes-devkit==1.1.9
      - oauthlib==3.2.1
      - onnx==1.17.0
      - onnx-simplifier==0.4.36
      - onnxruntime==1.19.2
      - opencv-python-headless==4.5.5.64
      - packaging==21.3
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pip==22.0.3
      - plyfile==0.7.4
      - portalocker==2.5.1
      - proglog==0.1.12
      - prometheus-client==0.13.1
      - prompt-toolkit==3.0.28
      - protobuf==3.20.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pycocotools==2.0.4
      - pycparser==2.23
      - pygments==2.19.2
      - pyparsing==3.0.6
      - pyquaternion==0.9.9
      - pyrsistent==0.18.1
      - python-dateutil==2.8.2
      - pyyaml==6.0
      - pyzmq==22.3.0
      - qtconsole==5.2.2
      - qtpy==2.0.1
      - requests==2.28.1
      - requests-oauthlib==1.3.1
      - rich==14.2.0
      - rsa==4.9
      - scikit-learn==1.0.2
      - scipy==1.7.1
      - send2trash==1.8.0
      - setuptools==59.5.0
      - shapely==1.8.1.post1
      - six==1.17.0
      - stack-data==0.2.0
      - sympy==1.13.3
      - tabulate==0.8.10
      - tensorboard==2.10.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorboardx==2.4
      - termcolor==1.1.0
      - terminado==0.13.1
      - testpath==0.6.0
      - threadpoolctl==3.1.0
      - timm==0.4.12
      - torchprofile==0.0.4
      - torchviz==0.0.3
      - tornado==6.1
      - tqdm==4.62.3
      - traitlets==5.1.1
      - urllib3==1.26.12
      - wcwidth==0.2.5
      - webencodings==0.5.1
      - werkzeug==2.2.2
      - wheel==0.37.1
      - widgetsnbextension==3.5.2
      - yacs==0.1.8
      - yapf==0.32.0
      - zipp==3.7.0
prefix: /work/sme-wangzr/wan_tao/miniconda3/envs/want_cmnext
